### ISSUE TITLE
Add ability to results in a standard format

### ISSUE THREAD

**Issue by Krinkle** [MusikAnimal/global-search#6]
Hi,

Thanks for providing this awesome tool, providing "mwgrep"-like functionality to the masses.

It'd be great if users could export the data in some kind of standard format, like TSV or JSON. This would then allow the results to be fed to a tool like Tourbout (ref https://github.com/Krinkle/mw-tool-tourbot/issues/11).

**Comment by MusikAnimal** [comment]
I think this is a great idea! I've created a task at https://phabricator.wikimedia.org/T233049. I'll close the Issues on this GitHub repo, and make it more clear there's a Phab board. Thanks
